server:
  http:
    addr: 0.0.0.0:8020
    timeout: 100s
  grpc:
    addr: 0.0.0.0:9020
    timeout: 100s
data:
  database:
    driver: mysql
    source: root:8888.216@tcp(127.0.0.1:3306)/lehu_video_db?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 20s
    write_timeout: 20s
    password: "8888.216"
    db: 0
  minio:
    host: localhost
    port: "9000"
    console_port: "9001"
    access_key: minioadmin
    secret_key: minioadmin

data_setting:
  db_sharding_config:
    file_shortvideo_short_video:
      sharding: file_shortvideo_short_video
      sharding_number: 5
    file_shortvideo_public:
      sharding: file_shortvideo_public
      sharding_number: 5
  db_sharding_tables:
    file:
      domain_name: shortvideo
      biz_sharding_field_config:
        short_video:
          fields:
            - id
            - hash
        public:
          fields:
            - id
            - hash
